spring:
  jooq:
    sql-dialect: postgres
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:15432/avocado_dev?schema=public
    username: avocado
    password: test1234

logging:
  level:
    org.springframework.r2dbc: TRACE
    io.r2dbc.postgresql.QUERY: TRACE
    io.r2dbc.postgresql.PARAM: TRACE
